# Pipeline configuration
root_dir: "./"
chat_name: "fart_noises_for_life"
input_chat_text_dir: "data/01_raw"

run_loader: False
loaded_chat_parquet_dir: "data/02_loaded/"

run_features: False
features_chat_parquet_dir: "data/04_featured/"

run_model_training: True
trained_model_pickle_dir: "data/05_model/"

run_model_prediction: True
seed: "there once was a human named sam"